# Name your project
name: 'stock_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery'

# These directories tell dbt where to find different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  stock_analytics:
    # Config for all models in the models/staging directory
    staging:
      +materialized: view
      +schema: staging
    
    # Config for all models in the models/marts directory
    marts:
      +materialized: table
      +schema: marts 