version: 2

models:
  - name: stg_stock_data
    description: "Cleaned and standardized stock market data from raw source"
    columns:
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
      - name: open
        description: "Opening price"
      - name: high
        description: "Highest price during trading day"
      - name: low
        description: "Lowest price during trading day"
      - name: close
        description: "Closing price"
      - name: adjusted_close
        description: "Closing price adjusted for dividends and splits"
      - name: volume
        description: "Trading volume"

sources:
  - name: bigquery_raw
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: stock_market_data
    tables:
      - name: stock_data_raw
        description: "Raw stock market data from yfinance API" 

  - name: stock_market_data
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: stock_market_data
    tables:
      - name: price_predictions
        description: "ML model predicted stock prices"
        columns:
          - name: symbol
            description: "Stock ticker symbol"
          - name: prediction_date
            description: "Date of the prediction"
          - name: predicted_close
            description: "Predicted closing price"
          - name: current_close
            description: "Current closing price at time of prediction"
          - name: predicted_change
            description: "Predicted absolute price change"
          - name: predicted_change_pct
            description: "Predicted percentage price change"
            
      - name: model_metrics
        description: "Performance metrics for trained ML models"
        columns:
          - name: symbol
            description: "Stock ticker symbol"
          - name: mse
            description: "Mean Squared Error"
          - name: r2
            description: "R-squared value"
          - name: model_type
            description: "Type of model (e.g., random_forest)"
          - name: training_date
            description: "Date when the model was trained" 